#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/17623/source/repos/RitchieLing/A1_A3_student_template/cpsc-427-dev/template/"
